### ISSUE TITLE
make the exportLogDataToJSON supporting the ZonedDateTime format

### ISSUE THREAD

**Issue by mickaelgobbo** [adobe/log-parser#185]
### Expected Behaviour
This should be fine to have the different exportLogDataToJSON method supporting the java.time.ZonedDateTime format.

### Actual Behaviour
Currently it's not the case, and in the structure of the logData which need to be exported, if a java.time.ZonedDateTime is present, we have the issue:

```
Encountered error while exporting the log data to a JSON file.
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Java 8 date/time 
type `java.time.ZonedDateTime` not supported by default: add Module "com.fasterxml.jackson.datatype:jackson-datatype-jsr310" to enable handling (through 
reference chain: java.util.ArrayList[0]->java.util.HashMap["timestamp"])
```

**Comment by baubakg** [comment]
problem reproduced

**Comment by baubakg** [comment]
Two elements:
* We should be resilient, as in we need to throw errors in a correct fashion. There should be a dedicated exception, with proper workaround mechanisms
* We should use the Jacksons java8 datetime mechanisms
