### ISSUE TITLE
Add table of contents

### ISSUE THREAD

**Issue by baubakg** [adobe/log-parser#47]
The doc needs a table of contents. For this you can use
https://luciopaiva.com/markdown-toc/

**Comment by kuruvasatya** [comment]
Hey @baubakg, I can work on this, please assign this to me

**Comment by baubakg** [comment]
Reference is:
https://github.com/adobe/phased-testing

**Comment by baubakg** [comment]
Corected by https://github.com/adobe/log-parser/pull/49
